[package]
name = "dab-rs"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.69.4"
cc = "1.1.7"

[dependencies]
minifb = "0.27.0"
plotters = "0.3.6"
plotters-bitmap = "0.3.6"
rustfft = "6.2.0"
