[package]
name = "dab-rs"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.69.4"
cc = "1.1.7"

[dependencies]
bitvec = "1"
libm = "0.2.8"
minifb = "0.27.0"
plotters = "0.3.6"
plotters-bitmap = "0.3.6"
rustfft = "6.2.0"
clap = { version = "4.5.20", features = ["derive"] }